apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: python  
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      imagePullSecrets:
      - name: secret-app
      containers:
      - image: 040500316512.dkr.ecr.eu-central-1.amazonaws.com/python_app:latest
        name: my-app-py
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 0.5
            memory: 200Mi
          requests:
            cpu: 0.1
            memory: 100Mi
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
